### PR TITLE
fix: skip sending status code after body is sent

### LINKED ISSUE #32: Have something wrong with the response of localhost:8001/metrics
Hello,
    I followed the official Doc of the [Prometheus](https://docs.konghq.com/hub/kong-inc/prometheus/)
and I tried http://localhost:8001/metrics but hava something wrong with reponse.  I'm not sure if it's a prometheus plugin issue or something I'm doing wrong. Thank you for reading 

Kong Version 1.0.0rc2

localhost:8001/plugins

`{
next: null,
data: [
{
created_at: 1544434246,
config: { },
id: "020666d3-0f39-4fc2-80e6-6b8a9534d1c4",
service: {
id: "de838225-be9c-4e5c-99e1-f21b47970e03"
},
name: "prometheus",
api: null,
consumer: null,
route: null,
enabled: true
},
{
created_at: 1544497752,
config: { },
id: "302d6c16-e4ba-4574-b589-c27ed3bb6829",
service: null,
name: "prometheus",
api: null,
consumer: null,
route: null,
enabled: true
}
]
}`

localhost:8001/metrics

<pre>
# HELP kong_datastore_reachable Datastore reachable from Kong, 0 is unreachable
# TYPE kong_datastore_reachable gauge
kong_datastore_reachable 1
# HELP kong_nginx_http_current_connections Number of HTTP connections
# TYPE kong_nginx_http_current_connections gauge
kong_nginx_http_current_connections{state="accepted"} 19
kong_nginx_http_current_connections{state="active"} 1
kong_nginx_http_current_connections{state="handled"} 19
kong_nginx_http_current_connections{state="reading"} 0
kong_nginx_http_current_connections{state="total"} 131
kong_nginx_http_current_connections{state="waiting"} 0
kong_nginx_http_current_connections{state="writing"} 1
# HELP kong_nginx_metric_errors_total Number of nginx-lua-prometheus errors
# TYPE kong_nginx_metric_errors_total counter
kong_nginx_metric_errors_total 0
{"message":"An unexpected error occurred"}
</pre>

error.log of Kong

<pre>
2018/12/11 11:12:03 [error] 2303#0: *8748 [lua] init.lua:143: handle_error(): /usr/local/share/lua/5.1/lapis/application.lua:397: /usr/local/share/lua/5.1/kong/plugins/prometheus/api.lua:20: headers have already been sent
stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/kong/pdk/response.lua:553: in function 'collect'
        /usr/local/share/lua/5.1/kong/plugins/prometheus/api.lua:20: in function </usr/local/share/lua/5.1/kong/plugins/prometheus/api.lua:19>

stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/lapis/application.lua:397: in function 'handler'
        /usr/local/share/lua/5.1/lapis/application.lua:130: in function 'resolve'
        /usr/local/share/lua/5.1/lapis/application.lua:161: in function </usr/local/share/lua/5.1/lapis/application.lua:159>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/lapis/application.lua:159: in function 'dispatch'
        /usr/local/share/lua/5.1/lapis/nginx.lua:215: in function 'serve_admin_api'
        content_by_lua(nginx-kong.conf:175):2: in function <content_by_lua(nginx-kong.conf:175):1>, client: 223.104.5.223, server: kong_admin, request: "GET /metrics HTTP/1.1", host: "115.159.34.56:8001"
2018/12/11 11:12:03 [error] 2303#0: *8748 attempt to set ngx.status after sending out response headers, client: 223.104.5.223, server: kong_admin, request: "GET /metrics HTTP/1.1", host: "115.159.34.56:8001"
2018/12/11 11:12:03 [error] 2303#0: *8748 attempt to set ngx.header.HEADER after sending out response headers, client: 223.104.5.223, server: kong_admin, request: "GET /metrics HTTP/1.1", host: "115.159.34.56:8001"
2018/12/11 11:12:03 [error] 2303#0: *8748 attempt to set ngx.header.HEADER after sending out response headers, client: 223.104.5.223, server: kong_admin, request: "GET /metrics HTTP/1.1", host: "115.159.34.56:8001"
2018/12/11 11:12:03 [error] 2303#0: *8748 attempt to set ngx.header.HEADER after sending out response headers, client: 223.104.5.223, server: kong_admin, request: "GET /metrics HTTP/1.1", host: "115.159.34.56:8001"
2018/12/11 11:12:03 [error] 2303#0: *8748 attempt to set status 500 via ngx.exit after sending out the response status 200, client: 223.104.5.223, server: kong_admin, request: "GET /metrics HTTP/1.1", host: "115.159.34.56:8001"
</pre>

### PR DESCRIPTION
**Pull request by hbagdi**
This commit fixes a bug where the plugin tries to send HTTP status code
after the response body is sent for `/metrics` endpoint.

This resulted in error logs in Kong.
A test has been added to ensure that no error logs are generated when
`/metrics` is scraped by Prometheus.

Another test has been added to ensure that the response body only
contains either metrics or comments describing the metrics.
This test is added to catch regression for
https://github.com/Kong/kong/pull/4077, where Kong injected HTML
generated by the default Lapis handler.

Fixes #32

### CODE REVIEW

File: kong/plugins/prometheus/exporter.lua [hunk 1]
```diff
@@ -121,7 +121,7 @@ local function collect()
   end
 
   prometheus:collect()
-  return kong.response.exit(200)
+  return
```
Comment (hishamhm) [inline kong/plugins/prometheus/exporter.lua]: you can simply delete this line now :)
